//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MobileOperator
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Collections.Generic;
    
    public class Number
    {
        public Number()
        {
            this.Contracts = new HashSet<Contract>();
        }
        
        [Key]
        public string Number_telephone { get; set; }
        
        public short rate_ID { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }

        public virtual Rate Rate { get; set; }
    }
}
