//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOperator
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Rate
    {
        public Rate()
        {
            this.Numbers = new HashSet<Number>();
        }

        [Key]
        public short rate_ID { get; set; }

        public string Name_rate { get; set; }

        public short Cost { get; set; }

        public short Internet { get; set; }

        public short Minutes { get; set; }

        public short SMS { get; set; }
    
        public virtual ICollection<Number> Numbers { get; set; }
    }
}
